version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=atendimento
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "80:80"

volumes:
  mysql:
